"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, ArrowRight, Lightbulb, Mic2 } from "lucide-react";

const LESSONS = [
  { id: 1, title: "Finding Your Speaking Voice", concept: "The most compelling speakers sound like themselves — amplified. Not like a robot, not like a presenter, like a more focused, more confident version of who they actually are.", tips: ["Record yourself in casual conversation, then in a speech. What changes? Why?", "Write your speech how you'd explain it to a friend, then refine", "Avoid 'presenter voice' — it signals inauthenticity immediately", "Your natural conversational rhythm is your best asset — keep it"], takeaway: "Authenticity is not a style. It's the absence of performing." },
  { id: 2, title: "Advanced Articulation", concept: "Beyond basic clarity, advanced articulation is about rhythm, emphasis, and the physical precision of difficult sounds.", techniques: [{ name: "Consonant Crisping", desc: "Overemphasise hard consonants in practice (T, K, P, B) so they land naturally in performance." }, { name: "Vowel Extension", desc: "Sustain your vowels slightly longer on key words — it creates richness and gravity." }, { name: "Word Stress Shifting", desc: "Try stressing different words in the same sentence and notice how the meaning shifts entirely." }, { name: "Rhythm Variation", desc: "Vary the number of syllables per beat. A string of three-syllable words builds momentum. A single syllable word stops it." }], takeaway: "Articulation at Level 2 is not about being understood — it's about being felt." },
  { id: 3, title: "Storytelling Structure", concept: "Stories are the most powerful delivery vehicle for any message. The human brain is wired for narrative — facts are forgotten, stories are remembered.", arc: [{ part: "Normal World", desc: "Set the scene. Show us life before the problem. Make us care about the character." }, { part: "The Problem", desc: "Something disrupts the normal world. Create tension — this is where attention spikes." }, { part: "The Journey", desc: "Attempts to solve the problem. What did you try? What went wrong? What did you learn?" }, { part: "Resolution", desc: "The solution or the lesson. What's different now? What does it mean?" }, { part: "Message", desc: "Connect the story explicitly to your speech's main point. Don't assume they'll do it themselves." }], takeaway: "The audience doesn't remember what you said. They remember how you made them feel." },
  { id: 4, title: "Ethos, Pathos, Logos", concept: "Aristotle's three pillars of persuasion are still the most powerful framework for any speech that needs to move an audience.", pillars: [{ name: "Ethos — Credibility", color: "text-blue-400", desc: "Why should they trust you? Establish your right to speak on this topic. Credentials, experience, or demonstrated understanding all work." }, { name: "Pathos — Emotion", color: "text-rose-400", desc: "Why should they care? Connect to a human need, fear, desire, or value. Statistics don't move people — stories do." }, { name: "Logos — Logic", color: "text-emerald-400", desc: "Why should they believe you? Evidence, data, examples, and logical reasoning. Back every claim with proof." }], takeaway: "The most persuasive speeches use all three in balance. Ethos opens the door. Pathos moves people through it. Logos gives them permission to follow." },
  { id: 5, title: "Audience Management", concept: "A speech is not a performance at an audience — it's a conversation with one. Great speakers constantly read and respond to the room.", skills: ["Watch for body language signals: crossed arms, looking at phones, leaning forward", "Adjust your energy to match and slightly exceed the room's energy", "Ask rhetorical questions to re-engage a drifting audience", "Pause and make direct eye contact if you feel the room slipping", "Name the tension: 'I can see some of you are sceptical — let me address that'"], takeaway: "The best speakers don't just talk — they listen with their eyes." },
  { id: 6, title: "Advanced Body Language", concept: "At Level 2, body language goes beyond posture. It becomes a deliberate communication tool — every movement carries meaning.", elements: [{ name: "Purposeful Movement", desc: "Move with intention. Step forward for emphasis, step back to give the audience space to absorb." }, { name: "Gesture Timing", desc: "Your gesture should arrive with or slightly before the word it emphasises — not after." }, { name: "Stage Ownership", desc: "Use the full space available to you. A speaker who stays in one spot sends a signal of anxiety." }, { name: "Facial Congruence", desc: "Your face must match your words. Smiling while talking about a serious topic destroys trust." }], takeaway: "Every movement you make on stage is either communicating something or taking away from your words. Make every movement mean something." },
  { id: 7, title: "The Power of the Pause", concept: "Most speakers fear silence. The best speakers weaponise it. A well-timed pause is worth ten words.", uses: ["After a key point — let it land before moving on", "Before a reveal — build anticipation", "After a question — let the audience actually think", "When you're transitioning — signal a change in direction", "When you've made an emotional point — let them feel it"], takeaway: "Silence after a powerful statement says: 'That was important enough to sit with.' Never rush past your best moment." },
  { id: 8, title: "Practice: 3-Minute Persuasive Speech", concept: "Choose a topic you genuinely care about and write a speech that uses all three pillars — Ethos, Pathos, and Logos — to move your audience to action.", tips: ["Start with an emotional hook (Pathos)", "Establish your credibility early (Ethos)", "Back your central claim with evidence (Logos)", "End with a specific call to action — tell them exactly what to do"], takeaway: "Persuasion is not about winning an argument. It's about helping someone see something they already knew was true." },
];

export default function SpeakingLevel2() {
  const [openLesson, setOpenLesson] = useState(0);
  return (
    <div className="flex flex-col gap-3">
      {LESSONS.map((lesson, i) => {
        const open = openLesson === i;
        return (
          <div key={lesson.id} className="glass-card overflow-hidden rounded-2xl">
            <button onClick={() => setOpenLesson(open ? -1 : i)} className="flex w-full items-center gap-4 p-5 text-left">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-violet-500"><Mic2 size={16} className="text-white" /></div>
              <div className="flex-1"><span className="text-xs font-semibold text-[#94A3B8]">Lesson {lesson.id}</span><p className="font-semibold text-[#F1F5F9]">{lesson.title}</p></div>
              {open ? <ChevronUp size={16} className="shrink-0 text-[#94A3B8]" /> : <ChevronDown size={16} className="shrink-0 text-[#94A3B8]" />}
            </button>
            {open && (
              <div className="border-t border-[#1E293B] px-5 pb-5 pt-4 space-y-4">
                <p className="text-sm leading-relaxed text-[#94A3B8]">{lesson.concept}</p>
                {"tips" in lesson && (lesson as {tips:string[]}).tips.map((t, idx) => <div key={idx} className="flex gap-2"><ArrowRight size={14} className="mt-0.5 shrink-0 text-violet-400" /><p className="text-sm text-[#94A3B8]">{t}</p></div>)}
                {"techniques" in lesson && <div className="grid gap-2 sm:grid-cols-2">{(lesson as {techniques:{name:string;desc:string}[]}).techniques.map((t) => <div key={t.name} className="rounded-xl border border-[#1E293B] bg-[#0A0F1E] p-3"><p className="mb-0.5 text-sm font-semibold text-violet-400">{t.name}</p><p className="text-xs text-[#94A3B8]">{t.desc}</p></div>)}</div>}
                {"arc" in lesson && (lesson as {arc:{part:string;desc:string}[]}).arc.map((a, idx) => <div key={idx} className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-500/20 text-xs font-bold text-violet-400">{idx+1}</span><div><p className="text-sm font-semibold text-[#F1F5F9]">{a.part}</p><p className="text-xs text-[#94A3B8]">{a.desc}</p></div></div>)}
                {"pillars" in lesson && <div className="flex flex-col gap-3">{(lesson as {pillars:{name:string;color:string;desc:string}[]}).pillars.map((p) => <div key={p.name} className="rounded-xl border border-[#1E293B] bg-[#0A0F1E] p-4"><p className={`mb-1 font-bold text-sm ${p.color}`}>{p.name}</p><p className="text-sm text-[#94A3B8]">{p.desc}</p></div>)}</div>}
                {"skills" in lesson && (lesson as {skills:string[]}).skills.map((s, idx) => <div key={idx} className="flex gap-2"><ArrowRight size={14} className="mt-0.5 shrink-0 text-violet-400" /><p className="text-sm text-[#94A3B8]">{s}</p></div>)}
                {"elements" in lesson && <div className="grid gap-2 sm:grid-cols-2">{(lesson as {elements:{name:string;desc:string}[]}).elements.map((el) => <div key={el.name} className="rounded-xl border border-[#1E293B] bg-[#0A0F1E] p-3"><p className="mb-0.5 text-sm font-semibold text-violet-400">{el.name}</p><p className="text-xs text-[#94A3B8]">{el.desc}</p></div>)}</div>}
                {"uses" in lesson && (lesson as {uses:string[]}).uses.map((u, idx) => <div key={idx} className="flex gap-2"><ArrowRight size={14} className="mt-0.5 shrink-0 text-violet-400" /><p className="text-sm text-[#94A3B8]">{u}</p></div>)}
                <div className="rounded-xl border border-violet-500/30 bg-violet-500/10 px-4 py-3"><div className="flex gap-2"><Lightbulb size={14} className="mt-0.5 shrink-0 text-violet-400" /><p className="text-sm font-medium text-[#F1F5F9]">{lesson.takeaway}</p></div></div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
