"use client";

import { useState } from "react"
import { ChevronDown, ChevronUp, ArrowRight, Lightbulb, Trophy } from "lucide-react";

const LESSONS = [
  { id: 1, title: "Adapting to Different Contexts", concept: "The same content delivered in front of a class, a TEDx audience, and a hiring panel requires three completely different styles. Mastery is knowing which to use and switching instantly.", contexts: [{ type: "Formal/Competition", style: "Precise language, structured arguments, no filler, controlled energy" }, { type: "Academic/Educational", style: "Clear explanations, logical flow, credible evidence, neutral tone" }, { type: "Inspirational/Keynote", style: "Stories, emotion, personal vulnerability, high energy" }, { type: "Professional/Interview", style: "Concise, specific, achievement-focused, confident but not aggressive" }], takeaway: "Read the room before you speak. The audience's context tells you everything about the style they expect." },
  { id: 2, title: "Event-Specific Mastery", concept: "Every speaking format has unwritten rules. Violating them signals inexperience — even if your content is excellent.", formats: [{ name: "TEDx Talk", rules: "Your idea must be stated clearly by minute 2. Personal story is required. No slides with bullet points. End with your idea restated in a new way." }, { name: "Valedictorian Speech", rules: "Must reference specific shared memories. Avoid generic graduation clichés. Earn every emotion — don't manufacture it." }, { name: "Competition Speech", rules: "Judges are looking for: organisation, evidence, delivery, and impact. Every second of your time limit should be filled deliberately." }, { name: "College Interview", rules: "Specificity always beats generality. 'I led a team of 12 to win nationals' beats 'I'm a good leader' every time." }], takeaway: "Study the event before you write a single word. Format first, content second." },
  { id: 3, title: "Advanced Persuasion Techniques", concept: "At performance level, persuasion is not just structure — it's the management of the audience's emotional journey from the first second to the last.", techniques: [{ name: "The Delayed Reveal", desc: "Tease your main point without stating it. Let the audience lean in before you land it." }, { name: "Narrative Tension", desc: "Every story needs a moment where the outcome is genuinely uncertain. No tension = no engagement." }, { name: "The Concession Move", desc: "Acknowledge the strongest counterargument before your audience can object. Then dismantle it. This builds enormous credibility." }, { name: "Callback", desc: "Return to an image, phrase, or idea from your opening in your close. It creates a sense of resolution and makes the speech feel complete." }], takeaway: "The audience should feel like the speech was made for them personally. That's not an accident — it's craft." },
  { id: 4, title: "Handling Q&A and Live Pressure", concept: "Q&A is where many speakers lose the room after winning it. It requires a different skill set from prepared delivery.", strategies: ["Repeat or paraphrase the question — it buys thinking time and ensures everyone heard it", "Answer with a 3-part structure: direct answer → brief explanation → example", "If you don't know: 'That's a great question I'd want to think more carefully about — let me follow up'", "Handle hostile questions by validating the concern, then redirecting: 'I understand the concern. Here's what the evidence shows...'", "Control the close: don't let Q&A end your event. Take the mic back and deliver a final 30-second conclusion"], takeaway: "Q&A is not a test of knowledge. It's a test of composure. The calmest voice in the room wins." },
  { id: 5, title: "Performing Under Pressure", concept: "The physiological response to high-stakes speaking is identical to physical danger. Understanding this removes the mystery and the power it has over you.", tools: ["Physical anchoring: press your feet into the floor before you speak. It grounds your body.", "The 6-second rule: if something goes wrong, wait 6 seconds before reacting. It always looks better to the audience than it feels.", "Pre-performance ritual: the same 3 actions done before every speech trains your brain to associate them with performing well.", "Visualise the end, not the beginning: see yourself landing your final line perfectly. Then build backward.", "Fail forward: if you lose your place, pause, breathe, and continue. Nobody leaves a speech remembering a moment of silence."], takeaway: "Pressure is privilege. It means what you're doing matters. Let it fuel you." },
  { id: 6, title: "Vocal Stamina for Long Speeches", concept: "A speech that starts at 9/10 and fades to 6/10 by the end leaves the audience with the ending — which is what they remember.", practices: ["Hydrate constantly — your vocal cords are tissue and need moisture", "Never speak at full volume for more than 15 minutes without a dynamic shift", "Use pauses to let your voice rest, not just for emphasis", "Warm up: humming, lip trills, and tongue rolls before any major speech", "Know when you're tired: rushing = fatigue signal. Slow down intentionally."], takeaway: "Your voice is an instrument. Treat it like one — warm it up, rest it, and never blow it out the night before." },
  { id: 7, title: "The First 10 Seconds", concept: "Neuroscience is clear: audiences make their judgment of a speaker in the first 7-10 seconds. After that, you're either recovering credibility or spending it.", openers: [{ type: "The Bold Statement", example: "'Most of what you were taught about success is wrong.'" }, { type: "The Question", example: "'How many of you have ever felt like you didn't belong in the room you were in?'" }, { type: "The Statistic", example: "'Every 40 seconds, someone takes their own life. This talk is about the 39 seconds before that.'" }, { type: "The Story Opening", example: "'It was 3am. I had $12 in my account and a presentation to 500 people in 6 hours.'" }], takeaway: "Never start with 'Good morning'. Never start with 'My name is'. Never start with 'So'. Start with the speech." },
  { id: 8, title: "Practice: Full Event Simulation", concept: "Choose an event type, write a complete speech, and submit for performance-level feedback. This is your final practice before a real audience.", tips: ["Choose the event you'll face in real life soonest", "Write the full speech — not an outline", "Read it aloud at least twice before submitting", "Time it — every format has a time limit. Respect it."], takeaway: "There is no substitute for doing it. Submit the speech. Read the feedback. Do it again." },
];

export default function SpeakingLevel3() {
  const [openLesson, setOpenLesson] = useState(0);
  return (
    <div className="flex flex-col gap-3">
      {LESSONS.map((lesson, i) => {
        const open = openLesson === i;
        return (
          <div key={lesson.id} className="glass-card overflow-hidden rounded-2xl">
            <button onClick={() => setOpenLesson(open ? -1 : i)} className="flex w-full items-center gap-4 p-5 text-left">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-amber-500"><Trophy size={16} className="text-white" /></div>
              <div className="flex-1"><span className="text-xs font-semibold text-[#94A3B8]">Lesson {lesson.id}</span><p className="font-semibold text-[#F1F5F9]">{lesson.title}</p></div>
              {open ? <ChevronUp size={16} className="shrink-0 text-[#94A3B8]" /> : <ChevronDown size={16} className="shrink-0 text-[#94A3B8]" />}
            </button>
            {open && (
              <div className="border-t border-[#1E293B] px-5 pb-5 pt-4 space-y-4">
                <p className="text-sm leading-relaxed text-[#94A3B8]">{lesson.concept}</p>
                {"contexts" in lesson && <div className="grid gap-2 sm:grid-cols-2">{(lesson as {contexts:{type:string;style:string}[]}).contexts.map((c) => <div key={c.type} className="rounded-xl border border-[#1E293B] bg-[#0A0F1E] p-3"><p className="mb-0.5 text-sm font-semibold text-amber-400">{c.type}</p><p className="text-xs text-[#94A3B8]">{c.style}</p></div>)}</div>}
                {"formats" in lesson && <div className="flex flex-col gap-2">{(lesson as {formats:{name:string;rules:string}[]}).formats.map((f) => <div key={f.name} className="rounded-xl border border-[#1E293B] bg-[#0A0F1E] p-3"><p className="mb-1 text-sm font-semibold text-amber-400">{f.name}</p><p className="text-xs text-[#94A3B8]">{f.rules}</p></div>)}</div>}
                {"techniques" in lesson && <div className="flex flex-col gap-2">{(lesson as {techniques:{name:string;desc:string}[]}).techniques.map((t) => <div key={t.name} className="rounded-xl border border-[#1E293B] bg-[#0A0F1E] p-3"><p className="mb-0.5 text-sm font-semibold text-amber-400">{t.name}</p><p className="text-xs text-[#94A3B8]">{t.desc}</p></div>)}</div>}
                {"strategies" in lesson && (lesson as {strategies:string[]}).strategies.map((s, idx) => <div key={idx} className="flex gap-2"><ArrowRight size={14} className="mt-0.5 shrink-0 text-amber-400" /><p className="text-sm text-[#94A3B8]">{s}</p></div>)}
                {"tools" in lesson && (lesson as {tools:string[]}).tools.map((t, idx) => <div key={idx} className="flex gap-2"><ArrowRight size={14} className="mt-0.5 shrink-0 text-amber-400" /><p className="text-sm text-[#94A3B8]">{t}</p></div>)}
                {"practices" in lesson && (lesson as {practices:string[]}).practices.map((p, idx) => <div key={idx} className="flex gap-2"><ArrowRight size={14} className="mt-0.5 shrink-0 text-amber-400" /><p className="text-sm text-[#94A3B8]">{p}</p></div>)}
                {"openers" in lesson && <div className="flex flex-col gap-2">{(lesson as {openers:{type:string;example:string}[]}).openers.map((o) => <div key={o.type} className="rounded-xl border border-[#1E293B] bg-[#0A0F1E] p-3"><p className="mb-1 text-xs font-semibold text-amber-400">{o.type}</p><p className="text-sm italic text-[#94A3B8]">{o.example}</p></div>)}</div>}
                {"tips" in lesson && (lesson as {tips:string[]}).tips.map((t, idx) => <div key={idx} className="flex gap-2"><ArrowRight size={14} className="mt-0.5 shrink-0 text-amber-400" /><p className="text-sm text-[#94A3B8]">{t}</p></div>)}
                <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3"><div className="flex gap-2"><Lightbulb size={14} className="mt-0.5 shrink-0 text-amber-400" /><p className="text-sm font-medium text-[#F1F5F9]">{lesson.takeaway}</p></div></div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
